<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-12T20:50:22 IST" name="Default suite" finished-at="2022-12-12T20:50:44 IST" duration-ms="22421">
    <groups>
    </groups>
    <test started-at="2022-12-12T20:50:22 IST" name="Default test" finished-at="2022-12-12T20:50:44 IST" duration-ms="22421">
      <class name="com.gcr.scripts.TC5">
        <test-method is-config="true" signature="generateReport()[pri:0, instance:com.gcr.scripts.TC5@58d75e99]" started-at="2022-12-12T20:50:22 IST" name="generateReport" finished-at="2022-12-12T20:50:22 IST" duration-ms="696" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateReport -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:com.gcr.scripts.TC5@58d75e99]" started-at="2022-12-12T20:50:23 IST" name="beforeClass" finished-at="2022-12-12T20:50:28 IST" duration-ms="4992" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="methodName(java.lang.reflect.Method)[pri:0, instance:com.gcr.scripts.TC5@58d75e99]" started-at="2022-12-12T20:50:28 IST" name="methodName" finished-at="2022-12-12T20:50:28 IST" duration-ms="33" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.gcr.scripts.TC5.LoginLogout_WebShop_Excel() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodName -->
        <test-method signature="LoginLogout_WebShop_Excel()[pri:0, instance:com.gcr.scripts.TC5@58d75e99]" started-at="2022-12-12T20:50:28 IST" name="LoginLogout_WebShop_Excel" finished-at="2022-12-12T20:50:41 IST" duration-ms="13646" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Log out123] but found [Log out]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Log out123] but found [Log out]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.gcr.scripts.TC5.LoginLogout_WebShop_Excel(TC5.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginLogout_WebShop_Excel -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:com.gcr.scripts.TC5@58d75e99]" started-at="2022-12-12T20:50:41 IST" name="afterClass" finished-at="2022-12-12T20:50:44 IST" duration-ms="2884" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.gcr.scripts.TC5 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
